*****Counter tests*****
rising_count: True
falling_count: True
down_count: True
value_reset: True
cycles_default: True
cycles_set_prev: True
cycles_after_set: True
range_max_value: True
range_max_cycles: True
range_min_nonzero_value: True
range_min_nonzero_cycles: True
invalid_id_-1: Counter id must be in range 0-31
invalid_id_32: Counter id must be in range 0-31
invalid_edge: invalid edge
invalid_direction: invalid direction
invalid_src_pin: Pin 'P16_7' does not support 'PERI_TR_IO_INPUT'.
invalid_max: max must be >= 0
invalid_min_ge_max: min must be < max
filter_ns_not_supported: filter_ns not supported
index_not_supported: index not supported
reset_not_supported: reset not supported
match_not_supported: match not supported
match_pin_not_supported: match_pin not supported
duplicate_counter_id: Counter(6) already created.
