*****Counter tests*****
rising_count: True
falling_count: True
down_count: True
value_reset: True
cycles_default: True
cycles_set_prev: True
cycles_after_set: True
range_max_value: True
range_max_cycles: True
range_min_nonzero_value: True
range_min_nonzero_cycles: True
invalid_id_-1: Counter id must be in range 0-31
invalid_id_32: Counter id must be in range 0-31
invalid_edge: invalid edge
invalid_direction: invalid direction
invalid_src_pin: Pin 'P16_7' does not support 'PERI_TR_IO_INPUT'.
invalid_min_negative: min must be >= 0
invalid_max_negative: max must be >= 0
invalid_min_ge_max: min must be < max
filter_ns_not_supported: filter_ns not supported
index_active: True
reset_active: True
match_init_get: True
match_set_prev: True
match_after_set: True
match_disable_prev: True
match_after_disable: True
match_init_out_of_range: match out of range
match_set_out_of_range: match out of range
irq_obj_reuse: True
irq_trigger_get: True
irq_trigger_set_prev: True
irq_rollover_cb: True
irq_flags_rollover: True
irq_match_cb: True
irq_match_flags: True
irq_index_cb: True
irq_bad_handler: handler must be None or callable
irq_not_initialised: not initialised
match_pin_not_supported: match_pin not supported
duplicate_counter_id: Counter(6) already created.
