pin out initial value 1:  True
pin out initial value 0:  True
pin out callable 1:  True
pin out callable 0:  True
pin out value high:  True
pin out value low:  True
pin out value toggled (0->1):  True
pin out value 0:  True
pin out value 1:  True
machine.Pin with mode=Pin.OUT + pull=Pin.PULL_UP is not supported
machine.Pin with mode=Pin.OUT + pull=Pin.PULL_DOWN is not supported
machine.Pin warning: initial value is ignored for Pin.IN mode
pin in with pull none initially high-z:  True
pin in with pull up initially 1:  True
pin in with pull down initially 0:  True
pin in value 1:  True
pin in value 0:  True
pin in writes 1 but strong out drives 0:  True
pin in pull is now pull up after writing 1:  True
pin in writes 0 but strong out drives 0:  True
pin in pull is now pull down after writing 0:  True
pin od with pull none initially high-z:  True
pin od with pull up initially 1:  True
pin od with pull up initially 0:  True
pin od with pull up but strong out drives 0:  True
pin od with pull up but strong out drives 1:  True
pin od with pull up writes 1:  True
pin od with pull up writes 0:  True
pin od with pull none writes 1:  True
pin od with pull none writes 0:  True
machine.Pin with mode=Pin.OPEN_DRAIN + pull=Pin.PULL_DOWN is not supported
pin out set mode:  True
pin out set pull:  True
pin out set drive:  True
